import Link from 'next/link'
import type { Metadata } from 'next'
import { isAllowedUrl } from '@/data/civic-data'
import { getGeminiModel } from '@/lib/ai/gemini-client'

export const revalidate = false;

export const metadata: Metadata = {
  title: 'Election Timelines · India Election Guide',
  description: 'Stay updated with official election schedules and voter registration deadlines.',
  openGraph: {
    title: 'Election Timelines · India Election Guide',
    description: 'Stay updated with official election schedules and voter registration deadlines.',
    url: 'https://india-election-guide.vercel.app/timeline',
    siteName: 'India Election Guide',
    images: [{ url: '/images/og.png', width: 1200, height: 630 }],
    locale: 'en_IN',
    type: 'website',
  },
}

export const MOCK_TIMELINES = [
  {
    state: 'National',
    event: 'General Elections 2024',
    status: 'Completed',
    date: 'Phase 1-7 complete',
    source: 'ECI Notification',
  },
  {
    state: 'Maharashtra',
    event: 'Legislative Assembly Elections',
    status: 'Live',
    date: 'Polling: November 20, 2024',
    source: 'ECI Schedule',
  },
  {
    state: 'Delhi',
    event: 'Special Summary Revision',
    status: 'Upcoming',
    date: 'Oct 29 – Nov 28, 2024',
    source: 'CEO Delhi',
  },
]

export async function getTimelineSummary() {
  if (!process.env.GEMINI_API_KEY) {
    return 'Official summary currently being updated. Please check official sources for latest status.';
  }
  
  try {
    const model = getGeminiModel();
    const prompt = `Based on the following election timelines, provide a 2-sentence plain-language summary of the current election landscape in India.
  
Timelines:
${JSON.stringify(MOCK_TIMELINES, null, 2)}`;
  
    const result = await model.generateContent(prompt);
    return result.response.text();
  } catch (err) {
    return 'Unable to generate summary at this time.';
  }
}

export default async function TimelinePage() {
  const summary = await getTimelineSummary();
  return (
    <div className="py-16">
      <div className="container-app">
        <header className="mb-12">
          <h1 className="text-4xl font-extrabold mb-4">Election Timelines</h1>
          <p className="text-text-secondary text-lg max-w-xl font-medium">
            Stay updated with official election schedules and voter registration deadlines.
          </p>
        </header>

        <div className="mb-12 p-8 bg-blue-50/50 border border-blue-100 rounded-2xl relative overflow-hidden">
          <div className="absolute top-0 left-0 w-1 h-full bg-primary" aria-hidden="true" />
          <h2 className="text-sm font-bold text-primary uppercase tracking-wider mb-2 flex items-center gap-2">
            <span aria-hidden="true">✨</span> AI Election Summary
          </h2>
          <p className="text-text-title text-lg font-medium leading-relaxed">
            {summary}
          </p>
          <p className="text-xs text-text-light mt-4 font-medium italic">
            Generated by Gemini AI based on current ECI schedules. Always verify with official sources.
          </p>
        </div>

        <div className="space-y-4">
          {MOCK_TIMELINES.map((item, i) => (
            <div
              key={i}
              className="bg-white border border-border p-8 rounded-[var(--radius-lg)] shadow-subtle flex flex-col md:flex-row md:items-center justify-between gap-6 hover:shadow-card transition-all"
            >
              <div className="space-y-2">
                <div className="flex items-center gap-3">
                  <span className={`text-[9px] font-bold uppercase tracking-[0.2em] px-2 py-1 rounded ${
                    item.status === 'Live' ? 'bg-red-50 text-red-700 border border-red-100' :
                    item.status === 'Upcoming' ? 'bg-blue-50 text-primary border border-blue-100' :
                    'bg-gray-100 text-gray-700 border border-gray-200'
                  }`}>
                    {item.status}
                  </span>
                  <span className="text-[11px] font-bold text-text-secondary uppercase tracking-widest">{item.state}</span>
                </div>
                <h3 className="text-2xl font-bold">{item.event}</h3>
                <p className="text-text-secondary font-medium">{item.date}</p>
              </div>
              
              <div className="flex items-center gap-4">
                <span className="text-[11px] font-bold text-text-light uppercase tracking-tighter">Source: {item.source}</span>
                {isAllowedUrl('https://eci.gov.in/elections/election-schedule/') && (
                  <a
                    href="https://eci.gov.in/elections/election-schedule/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="px-6 py-2.5 bg-bg-subtle border border-border rounded-xl text-xs font-bold text-navy hover:bg-gray-100 transition-all active:scale-95"
                  >
                    Details ↗
                  </a>
                )}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-20 p-10 bg-white border border-border rounded-[var(--radius-lg)] shadow-sm">
          <h2 className="text-xl font-bold mb-4 flex items-center gap-3">
            <span className="text-2xl" aria-hidden="true">📅</span> Registration Deadlines
          </h2>
          <p className="text-text-secondary leading-relaxed mb-8 max-w-2xl">
            You can register to vote up to 10 days before the last date of filing nominations. Check the specific schedule for your constituency on the ECI portal.
          </p>
          <Link href="/flow/register-new" className="text-primary font-bold hover:underline inline-flex items-center gap-2">
            Register now <span>→</span>
          </Link>
        </div>
      </div>
    </div>
  )
}
